spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/tutorial
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1231
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    password: 1231
server:
  port: 8081
custom:
  message: Hello Spring EmployeeService Local Server updated !!!!!
